pollatme/urls.py
from django.contrib import admin
from django.urls import include, path
from privacy import views as privacy_views
from django.conf.urls import handler404, handler403, handler500

urlpatterns = [
    path('', include('polls.urls')),
    path("admin/", admin.site.urls),
    path('accounts/', include('justsocialauth.urls')),
    path('privacy/', privacy_views.privacy_policy, name="privacy_policy")
]

handler403 = 'polls.views.error_pages.error_403'
handler404 = 'polls.views.error_pages.error_404'
handler500 = 'polls.views.error_pages.error_500'

polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('vote/<int:id>/', views.vote_redirect_view, name='vote'),
    path('vote/<int:id>/<str:token>/', views.vote_redirect_view, name='vote'),
    path('vote/singlepreference/<int:id>/', views.VoteSinglePreferenceView.as_view(), name = 'vote_single_preference'),
    path('vote/singlepreference/<int:id>/<str:token>', views.VoteSinglePreferenceView.as_view(), name = 'vote_single_preference'),
    path('vote/majorityjudgment/<int:id>/', views.VoteMajorityJudgmentView.as_view(), name = 'vote_MJ'),
    path('vote/majorityjudgment/<int:id>/<str:token>', views.VoteMajorityJudgmentView.as_view(), name = 'vote_MJ'),
    path('vote/schulze/<int:id>/', views.VoteShultzeView.as_view(), name = 'vote_shultze'),
    path('vote/schulze/<int:id>/<str:token>', views.VoteShultzeView.as_view(), name = 'vote_shultze'),

    path('result/<int:id>/', views.result_redirect_view, name='result'),
    path('result/singlepreference/<int:id>/', views.SinglePreferenceResultView.as_view(), name = 'result_single_preference'),
    path('result/majorityjudgment/<int:id>/', views.MajorityJudgementResultView.as_view(), name = 'result_MJ'),
    path('result/schulze/<int:id>/', views.ShultzePreferenceResultView.as_view(), name = 'result_shultze'),
    path('result/majorityjudgment/<int:id>/<str:include_synthetic>', views.MajorityJudgementResultView.as_view(), name = 'result_MJ_realonly'),
    
    path('new/', views.CreatePollView.as_view(), name='create_poll'),
    path('success/', views.CreatePollSuccessView.as_view(), name='poll_created_success'),
    path('delete/<int:pk>/', views.PollDeleteView.as_view(), name='delete_poll'),
    path('edit/<int:id>/', views.EditPollView.as_view(), name='edit_poll'),
    path('close/<int:id>/', views.poll_list.ClosePollView.as_view(), name='close_poll'),
    path('start/<int:id>/', views.poll_list.StartPollView.as_view(), name='start_poll'),
    path('search/', views.SearchView.as_view(), name='search_poll'),
    
    path('help/simulated_results/', views.HelpSimulatedResultsView.as_view(), name='help_simulated_results'),
    path('help/majorityjudgment/', views.ExplanationGMView.as_view(), name='explain_gm'),
    path('help/schulze_method/', views.ExplanationSchView.as_view(), name='explain_sch'),
    path('help/options/', views.ExplanationCreationPollView.as_view(), name='explain_options'),
    
    path('personal/', views.PersonalPollsView.as_view(), name='personal_polls'),
    path('<str:code>/<str:token>', views.AccessPollView.as_view(), name='access_poll'),
    path('<str:code>', views.AccessPollView.as_view(), name='access_poll'),
    
    path('tokens/<int:id>/', views.TokensView.as_view(), name='tokens'),
    path('tokens/<int:id>/download/', views.tokens_view.download_tokens, name='download_tokens'),
    path('tokens/<int:id>/success/', views.tokens_view.tokens_success, name='tokens_success'),
    path('tokens/<int:pk>/delete/', views.tokens_view.TokenDeleteView.as_view(), name='tokens_delete')
]

polls/models/alternative.py
from django.db import models

from .poll import Poll

class Alternative(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.text

polls/models/token.py
from django.db import models

class Token(models.Model):
    poll = models.ForeignKey('TokenizedPoll', on_delete=models.CASCADE)
    token = models.CharField(max_length=255)
    used = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "\""+self.token+"\" -> "+str(self.poll)+" ("+str(self.used)+")"

    def get_password_for_url(self) -> str:
        return self.token.replace(" ", "-")

polls/forms/token_gen_form.py
from django import forms

class TokenGeneratorForm(forms.Form):
    """
    A form class for generating between 1 and 20 random tokens.
    """
    tokens_to_be_generated = forms.IntegerField(
        min_value=1,
        max_value=20,
        label='Inserisci il numero di password da generare'
    )

polls/views/access_poll_view.py
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic.base import RedirectView

from polls.models.mapping import Mapping


class AccessPollView(RedirectView):
    """Redirects to vote or result pages, based on poll state"""

    def get_redirect_url(self, *args, **kwargs):

        mapping = get_object_or_404(Mapping, code=kwargs['code'])
        
        self.request.session['from_code'] = True

        poll = mapping.poll

        if poll.is_ended():
            self.url = reverse('polls:result', kwargs={'id': poll.pk})
        else:
            if 'token' in kwargs:
                redirect_args = {'id': poll.pk, 'token': kwargs['token']}
            else:
                redirect_args={'id': poll.pk}
            self.url = reverse('polls:vote', kwargs=redirect_args)
            
        return super().get_redirect_url(*args, **kwargs)

polls/views/create_poll_view.py
from typing import Any, Optional

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import QuerySet
from django import http
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView

from polls import forms
from polls import models
from polls.services import create_poll_service
from django.urls import reverse


ALTERNATIVE_FORMSET = forms.BaseAlternativeFormSet.get_formset_class()


def select_action(request: http.HttpRequest, poll=None):
    action, queryset_alternatives = ('create', models.Poll.objects.none(
    )) if poll is None else ('edit', poll.alternative_set.all())

    if 'summary' in request.POST:
        return summary(request, action, queryset_alternatives, poll)

    if 'go_back' in request.POST:
        return go_back(request, action, queryset_alternatives, poll)

    if 'save' in request.POST:
        return save(request, action, queryset_alternatives, poll)


def summary(request: http.HttpRequest, action: str, alternatives: QuerySet, poll: Optional[models.Poll] = None):
    form_mainpoll = forms.PollFormMain(request.POST, instance=poll)
    formset_alternatives: forms.BaseAlternativeFormSet = ALTERNATIVE_FORMSET(request.POST, queryset=alternatives)

    if form_mainpoll.is_valid() and formset_alternatives.is_valid():
        form_poll: models.Poll = form_mainpoll.get_temporary_poll()
        
        if action not in request.session:
            request.session[action] = {}

        request.session[action].update({
            'page_1': formset_alternatives.get_form_for_session()
        })

        saved_data = request.session[action].get('page_2')
        saved_data.update(request.POST.dict()) if saved_data is not None else None
        request.session.modified = True
        
        return render(request, f'polls/create_poll/summary_and_options_{action}.html', {
            'alternatives': formset_alternatives.get_alternatives_text_list(),
            'form': forms.PollForm(saved_data, instance = form_poll),
            'mapping_form': forms.PollMappingForm(saved_data, instance = form_poll.mapping),
            'options_form': forms.PollOptionsForm(saved_data, instance = form_poll.polloptions),
        })
    else:
        formset_alternatives._non_form_errors[0] = "Inserisci almeno due alternative." #type: ignore
        for dict in formset_alternatives.errors:
            if 'This field is required.' in str(dict):
                dict['text'] = ''  # type: ignore

        return render(request, f'polls/create_poll/main_page_{action}.html', {
            'form': form_mainpoll,
            'formset': formset_alternatives,
        })


def go_back(request: http.HttpRequest, action: str, alternatives: QuerySet, poll: Optional[models.Poll] = None):

    request.session[action]['page_2'] = request.POST.dict()
    request.session.modified = True
    
    return render(request, f'polls/create_poll/main_page_{action}.html', {
        'form': forms.PollFormMain(request.POST, instance=poll),
        'formset': ALTERNATIVE_FORMSET(request.session[action]['page_1'], queryset=alternatives)
    })


def save(request: http.HttpRequest, action: str, alternatives: QuerySet, poll: Optional[models.Poll] = None):
    form_poll = forms.PollForm(request.POST, instance=poll)
    formset_alternatives: forms.BaseAlternativeFormSet = ALTERNATIVE_FORMSET(request.session[action]['page_1'], queryset=alternatives)
    form_mapping = forms.PollMappingForm(request.POST, instance=poll.mapping if poll is not None else None)
    form_options = forms.PollOptionsForm(request.POST, instance=poll.polloptions if poll is not None else None)

    if all((form_poll.is_valid(), formset_alternatives.is_valid(), form_mapping.is_valid(), form_options.is_valid())):
        saved_poll = create_poll_service(request.user, form_poll, form_mapping, form_options, formset_alternatives) # type: ignore
        if hasattr(saved_poll, models.Poll.AUTH_VOTE_TYPE_FIELDNAME):
            vote_type = 'authenticated'
        elif hasattr(saved_poll, models.Poll.TOKEN_VOTE_TYPE_FIELDNAME):
            vote_type = 'tokenized'
        else:
            vote_type = 'free'
        
        request.session.update({
            'action': action,
            'id': saved_poll.id,
            'code': saved_poll.mapping.code,
            'title': saved_poll.title,
            'end': saved_poll.end.strftime('%d/%m/%Y %H:%M'),
            'vote_type': vote_type
        })
        request.session.modified = True

        return redirect(reverse('polls:poll_created_success'))
    else:
        return render(request, f'polls/create_poll/summary_and_options_{action}.html', {
            'form': form_poll,
            'alternatives': formset_alternatives.get_alternatives_text_list(),
            'mapping_form': form_mapping,
            'options_form': form_options,
        })


class CreatePollView(LoginRequiredMixin, TemplateView):

    def get(self, request: http.HttpRequest, *args, **kwargs):
        return render(request, 'polls/create_poll/main_page_create.html', {
            'form': forms.PollFormMain(),
            'formset': forms.BaseAlternativeFormSet.get_formset_class()(queryset=models.Poll.objects.none())
        })

    def post(self, request: http.HttpRequest, *args, **kwargs):
        return select_action(request)


class EditPollView(LoginRequiredMixin, TemplateView):

    def dispatch(self, request: http.HttpRequest, *args, **kwargs):
        self.__poll: models.Poll = get_object_or_404(models.Poll, id=kwargs['id'])

        if self.__poll.is_active():
            raise PermissionDenied(
                "Non è possibile modificare la scelta perché è in corso la votazione")

        if self.__poll.is_ended():
            raise PermissionDenied(
                "Questa scelta è conclusa e non può essere modificata")

        if not self.__poll.author.__eq__(request.user):
            raise PermissionDenied(
                "Non hai i permessi per modificare questa scelta")

        return super().dispatch(request, *args, **kwargs)

    def get(self, request: http.HttpRequest, *args, **kwargs):
        return render(request, 'polls/create_poll/main_page_edit.html', {
            'form': forms.PollFormMain(instance=self.__poll),
            'formset': forms.BaseAlternativeFormSet.get_formset_class()(queryset=self.__poll.alternative_set.all())
        })

    def post(self, request: http.HttpRequest, *args, **kwargs):
        return select_action(request, self.__poll)

class CreatePollSuccessView(LoginRequiredMixin, TemplateView):

    def get_template_names(self) -> list[str]:
        action = self.request.session.pop('action')
        return [f'polls/{action}_poll_success.html']

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        return {
            'id': self.request.session.pop('id'),
            'code': self.request.session.pop('code'),
            'title': self.request.session.pop('title'),
            'end': self.request.session.pop('end'),
            'vote_type': self.request.session.pop('vote_type')
        }

polls/views/delete_poll_view.py
from typing import Any, Optional

from django.db import models
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView

from polls.models import Poll
from polls.services import check

from django.contrib.auth.mixins import LoginRequiredMixin


class PollDeleteView(LoginRequiredMixin, DeleteView):
    model = Poll
    success_url = reverse_lazy('polls:personal_polls')
    http_method_names = ['post']

    def get_object(self, queryset: Optional[models.query.QuerySet[Any]] = None) -> models.Model:
        poll: Poll = super().get_object(queryset)

        handler = check.CheckPollIsNotStarted(poll)
        handler.set_next(check.CheckPollOwnership(poll, self.request.user))
        passed = handler.handle()

        return passed if passed else poll

polls/views/error_pages.py
from django.shortcuts import render

def error_403(request, exception):
    response = render(request, 'polls/403.html', {'exception': exception})
    response.status_code = 403
    return response

def error_404(request, exception):
    response = render(request, 'polls/404.html', {'exception': exception})
    response.status_code = 404
    return response

def error_500(request):
    response = render(request, 'polls/500.html')
    response.status_code = 500
    return response

polls/views/help_view.py
from django.views.generic.base import TemplateView

class ExplanationGMView(TemplateView):
    template_name = "polls/help/spiegazione_giudizio_maggioritario.html"

class ExplanationSchView(TemplateView):
    template_name = "polls/help/spiegazione_schultze.html"

class HelpSimulatedResultsView(TemplateView):
    template_name: str = 'polls/help/help_simulated_results.html'

class ExplanationCreationPollView(TemplateView):
    template_name: str = 'polls/help/help_advanced_options.html'

polls/views/poll_list.py
from datetime import datetime
from django.urls import reverse_lazy

from typing import Any, Optional, Type

from django import http
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Model, QuerySet
from django.shortcuts import render
from django.http import HttpResponseRedirect

from django.views.generic import FormView, View
from django.views.generic.list import ListView

from polls.forms import SearchPollForm
from polls.models import Poll
from polls.services import PollsListService
from polls.services.active_polls import SearchPollService
from polls.services import check


class IndexView(ListView):
    model: Optional[Type[Model]] = Poll
    paginate_by: int = 6
    template_name: str = 'polls/poll_list.html'

    def __init__(self, **kwargs: Any) -> None:
        self.__active_poll_service = PollsListService()
        super().__init__(**kwargs)

    def get_queryset(self) -> QuerySet[Poll]:
        return self.__active_poll_service.get_ordered_queryset(desc = False)


class SearchView(FormView):
    template_name: str = 'polls/search_poll.html'
    form_class = SearchPollForm

    def form_valid(self, form: SearchPollForm) -> http.HttpResponse:
        return render(self.request, 'polls/includes/poll_list.html', {
            'object_list': form.to_query().search()
        })

    def form_invalid(self, form: SearchPollForm) -> http.HttpResponse:
        return render(self.request, 'polls/includes/search_form.html', {
            'form': form
        })

class PersonalPollsView(LoginRequiredMixin, ListView):
    model: Optional[Type[Model]] = Poll
    paginate_by: int = 6
    template_name: str = 'polls/personal_polls.html'

    def __init__(self, **kwargs: Any) -> None:
        self.__active_poll_service = PollsListService()
        super().__init__(**kwargs)

    def get_queryset(self) -> QuerySet[Poll]:
        return self.__active_poll_service.get_my_polls(self.request.user)

class ClosePollView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request: http.HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponse:
        poll = SearchPollService().search_by_id(kwargs['id'])

        handler = check.CheckPollIsNotEnded(poll)
        handler.set_next(check.CheckPollOwnership(poll, self.request.user))
        handler.handle()
        
        if poll.results_restriction != 2:
            poll.end = datetime.now()
            poll.save()
        return HttpResponseRedirect(reverse_lazy('polls:personal_polls'))
    

class StartPollView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request: http.HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponse:
        poll = SearchPollService().search_by_id(kwargs['id'])
        
        handler = check.CheckPollIsNotStarted(poll)
        handler.set_next(check.CheckPollOwnership(poll, self.request.user))
        handler.handle()
        
        poll.start = datetime.now()
        poll.save()
        return HttpResponseRedirect(reverse_lazy('polls:personal_polls'))
        

templates/polls/edit_poll_success.html
{% extends 'layouts/base.html' %}

{% block title %} {{block.super}} | Scelta aggiornata! {% endblock title %}

{% block content %}
<div class="pcoded-main-container">
    <div class="pcoded-content">
        <div class="card">
            <div class="row align-items-center text-center">
                <div class="col-md-12">
                    <div class="card-body">
                        <h5>Fatto! La tua scelta è stata modificata.</h5>
                        <br>
                        <a class="btn btn-block btn-primary mb-4" href="/">
                            Torna alla home
                        </a>
                        <a class="btn btn-block btn-secondary mb-4" href="{% url 'polls:personal_polls' %}">
                            Scelte personali
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'polls/includes/footer.html' %}
</div>
{% endblock content %}

templates/polls/tokens_generation_success.html
{% extends 'layouts/base.html' %}

{% block title %} {{block.super}} | Password generate! {% endblock title %}

{% block content %}
<div class="pcoded-main-container">
    <div class="pcoded-content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="row align-items-center text-center">
                        <div class="col-md-12">
                            <div class="card-body">
                                <h3>Hai generato correttamente le password!</h3>
                                <br>
                                <a class="btn btn-block btn-secondary mb-4" href="{% url 'polls:index' %}">Torna alla home</a>
                                <a class="btn btn-block btn-primary mb-4" href="{% url 'polls:tokens' id=id %}">Pagina password</a>
                                <a class="btn btn-block btn-secondary mb-4" href="{% url 'polls:personal_polls' %}">Scelte personali</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card-body">
                                <table class="table">
                                    <thead>
                                      <tr>
                                        <th scope="col">Password generate</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      {% for password in generated %}
                                      <tr>
                                        <td>
                                            {{password}}
                                        </td>  
                                      </tr>
                                      {% endfor %}
                                    </tbody>
                                  </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'polls/includes/footer.html' %}
{% endblock content %}

templates/polls/tokens_page.html
{% extends 'layouts/base.html' %}

{% load django_bootstrap5 %}
{% load qr_code %}

{% block title %} {{block.super}} | Gestione password {% endblock title %}

{% block content %}

<div class="pcoded-main-container">
  <div class="pcoded-content">
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Gestione delle password</h3>
            <p class="card-text">
              Nella pagina corrente puoi gestire la generazione di password e il download del file PDF per poter
              stampare i bigliettini da distribuire ai votanti.
              Il file PDF che viene generato contiene tutti i i biglietti con i password ancora
              <strong>inutilizzati</strong> della scelta, suddivisi 8 per pagina. In fase di stampa, si consiglia
              di controllare le pagine che si desidera stampare, definendo un intervallo di pagine di stampa per evitare
              sprechi. Si ricorda infine che si possono generare da 1 a 20 password
              per volta e che una volta terminate le votazioni, non sarà più possibile accedere a questa pagina per
              generare o scaricare password.
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Informazioni di riepilogo</h5>
            <div class="row">
              <div class="col-sm-12">
                <div class="card bg-c-blue order-card">
                  <div class="card-body">
                    <h5 class="text-white">Titolo scelta: </h5>
                    <h2 class="text-end text-white"><span>{{poll.title}}</span>
                    </h2>
                    <h6 class="text-white">Data di apertura della scelta:</h6>
                    <h2 class="text-end text-white">
                      <em class="feather icon-calendar float-start"></em>
                      <span>{{ poll.start | date:"d/m/Y H:i" }}</span>
                    </h2>
                    <p class="m-b-0">Data di chiusura<span class="float-end">{{ poll.end | date:"d/m/Y H:i" }}</span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 col-xl-4">
                <div class="card bg-c-yellow order-card">
                  <div class="card-body">
                    <h5 class="text-white">Password generate: <span class="float-end"> {{ all_tokens }} </h5>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-xl-4">
                <div class="card bg-c-green order-card">
                  <div class="card-body">
                    <h5 class="text-white">Password disponibili: <span class="float-end"> {{ tokens_available }}</h5>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-xl-4">
                <div class="card bg-c-red order-card">
                  <div class="card-body">
                    <h5 class="text-white">Password utilizzate: <span class="float-end"> {{ tokens_used }}</h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="d-flex flex-row mb-4">
      <h5 class="card-title mt-2">Password generate</h5>
      <a href="{% url 'polls:download_tokens' id=poll.id %}" role="button" class="btn btn-danger p-2 ms-3 mb-3">
        Download PDF <i class="fas fa-file-pdf ms-2"></i>
      </a>
      <button type="button" data-bs-toggle="modal" data-bs-target="#generate-password"
        class="btn btn-secondary p-2 ms-3 mb-3">
        Genera
      </button>
    </div>
    <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-3">
      {% for token, link in object_list %}
      <div class="col">
        <div class="card h-100 border {% if token.used %} border-danger {% else %} border-success {% endif %}">
          <div class="card-body">
            <h6 class="card-text">{{ token.token }}
              {% if token.used %}<span class="badge rounded-pill bg-danger">Usato</span>{% endif %}
            </h6>
            {% if not token.used %}
            <div class="d-grid d-xl-flex gap-2">
              <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapse{{ token.id }}" aria-expanded="false" aria-controls="collapse{{ token.id }}">
                QR <span class="fas fa-qrcode me-2"></span>
              </button>
              <button class="btn btn-danger" type="button" data-bs-toggle="modal" data-bs-target="#modal-delete-confirm"
                data-bs-action="{% url 'polls:tokens_delete' pk=token.pk %}">
                Elimina <span class="fas fa-trash-alt me-2"></span></button>
              <button class="btn btn-success" type="button" data-bs-toggle="modal" data-bs-target="#modalPollSharing"
                data-bs-code="{{ poll.mapping.code|add:'/'|add:token.get_password_for_url }}"
                data-bs-public="{{ poll.is_public }}" data-bs-title="{{ poll.title }}" data-bs-end="{{ poll.end | date:"d/m/Y, H:i" }}">
                Condividi <span class="fas fa-share me-2"></span></button>
            </div>
            <div class="collapse mt-4 text-center" id="collapse{{ token.id }}">
              {% qr_from_text link size=8 border=1 %}
            </div>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <hr>
    {% include 'polls/includes/pagination.html' with page_obj=page_obj %}
    <div class="row">
      <div class="form-group text-center">
        <div class="col-sm-12 d-md-inline d-grid align-middle">
          <a class="btn btn-block btn-primary mb-3" href="/">Torna alla home</a>
          <a class="btn btn-block btn-secondary mb-3" href="{% url 'polls:personal_polls' %}">Scelte personali</a>
        </div>
      </div>
    </div>
  </div>
  {% include 'polls/includes/footer.html' %}
</div>

<div class="modal fade" id="generate-password" tabindex="-1" aria-labelledby="generate-password-label"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="generate-password-label">Genera nuove password</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="post">
        <div class="modal-body">
          {% csrf_token %}
          {% bootstrap_field form.tokens_to_be_generated show_label='skip' %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
          <button type="submit" class="btn btn-primary">Continua</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% include 'polls/includes/modal-poll_sharing.html' %}
{% include 'polls/includes/modal-delete.html' with msg='Vuoi veramente eliminare questa password?' id='modal-delete-confirm' %}

{% endblock content %}

templates/polls/vote_success.html
{% extends 'layouts/base.html' %}

{% block title %} {{block.super}} | Grazie per la risposta! {% endblock title %}

{% block content %}
<div class="pcoded-main-container">
    <div class="pcoded-content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="row align-items-center text-center">
                        <div class="col-md-12">
                            <div class="card-body">
                                <h2>Grazie!</h2>
                                <h5>La tua risposta è stata registrata!</h5>
                                <br>
                                <a href="{% url 'polls:index' %}" role="button" class="btn btn-block btn-primary mb-4"> Torna alla HOME </a>
                                <a href="{% url 'polls:result' id=poll.id %}" role="button" class="btn btn-block btn-primary mb-4"> Risultati scelta </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if revote %}
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="card align-items-center">
                        <div class="card-body text-center">
                            <h5>Vuoi esprimere la tua preferenza con un metodo diverso?</h5>
                            <a href="{% if token == '' %}{% url 'polls:vote_MJ' id=poll.id%}{% else %}{% url 'polls:vote_MJ' id=poll.id token=token%}{% endif %}" class="btn btn-block btn-primary mb-4">Giudica le alternative con il giudizio maggioritario</a>
                            <p class="card-text m-2">Il <b>giudizio maggioritario</b> è un metodo di scelta in cui
                                ogni votante esprime un giudizio per ogni alternativa.
                                I giudizi non sono numerici, ma sono delle valutazioni come "<i>ottimo</i>", "<i>buono</i>",
                                "<i>sufficiente</i>", "<i>scarso</i>" o "<i>pessimo</i>".
                                Al termine del voto, vengono combinate le valutazioni di tutti i votanti per ottenere un
                                giudizio complessivo per ogni alternativa.
                                Vince l'alternativa con il giudizio complessivo migliore.
                            </p>
                            <a href="{% url 'polls:explain_gm' %}" class="btn btn-primary btn-block">Scopri di più sul giudizio maggioritario</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
        {% endif %}
    </div>
    {% include 'polls/includes/footer.html' %}
</div>
{% endblock content %}