pollatme/urls.py
from django.contrib import admin
from django.urls import include, path
from privacy import views as privacy_views
from django.conf.urls import handler404, handler403, handler500

urlpatterns = [
    path('', include('polls.urls')),
    path("admin/", admin.site.urls),
    path('accounts/', include('justsocialauth.urls')),
    path('privacy/', privacy_views.privacy_policy, name="privacy_policy")
]

handler403 = 'polls.views.error_pages.error_403'
handler404 = 'polls.views.error_pages.error_404'
handler500 = 'polls.views.error_pages.error_500'

polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('vote/<int:id>/', views.vote_redirect_view, name='vote'),
    path('vote/<int:id>/<str:token>/', views.vote_redirect_view, name='vote'),
    path('vote/singlepreference/<int:id>/', views.VoteSinglePreferenceView.as_view(), name = 'vote_single_preference'),
    path('vote/singlepreference/<int:id>/<str:token>', views.VoteSinglePreferenceView.as_view(), name = 'vote_single_preference'),
    path('vote/majorityjudgment/<int:id>/', views.VoteMajorityJudgmentView.as_view(), name = 'vote_MJ'),
    path('vote/majorityjudgment/<int:id>/<str:token>', views.VoteMajorityJudgmentView.as_view(), name = 'vote_MJ'),
    path('vote/schulze/<int:id>/', views.VoteShultzeView.as_view(), name = 'vote_shultze'),
    path('vote/schulze/<int:id>/<str:token>', views.VoteShultzeView.as_view(), name = 'vote_shultze'),

    path('result/<int:id>/', views.result_redirect_view, name='result'),
    path('result/singlepreference/<int:id>/', views.SinglePreferenceResultView.as_view(), name = 'result_single_preference'),
    path('result/majorityjudgment/<int:id>/', views.MajorityJudgementResultView.as_view(), name = 'result_MJ'),
    path('result/schulze/<int:id>/', views.ShultzePreferenceResultView.as_view(), name = 'result_shultze'),
    path('result/majorityjudgment/<int:id>/<str:include_synthetic>', views.MajorityJudgementResultView.as_view(), name = 'result_MJ_realonly'),
    
    path('new/', views.CreatePollView.as_view(), name='create_poll'),
    path('success/', views.CreatePollSuccessView.as_view(), name='poll_created_success'),
    path('delete/<int:pk>/', views.PollDeleteView.as_view(), name='delete_poll'),
    path('edit/<int:id>/', views.EditPollView.as_view(), name='edit_poll'),
    path('close/<int:id>/', views.poll_list.ClosePollView.as_view(), name='close_poll'),
    path('start/<int:id>/', views.poll_list.StartPollView.as_view(), name='start_poll'),
    path('search/', views.SearchView.as_view(), name='search_poll'),
    
    path('help/simulated_results/', views.HelpSimulatedResultsView.as_view(), name='help_simulated_results'),
    path('help/majorityjudgment/', views.ExplanationGMView.as_view(), name='explain_gm'),
    path('help/schulze_method/', views.ExplanationSchView.as_view(), name='explain_sch'),
    path('help/options/', views.ExplanationCreationPollView.as_view(), name='explain_options'),
    
    path('personal/', views.PersonalPollsView.as_view(), name='personal_polls'),
    path('<str:code>/<str:token>', views.AccessPollView.as_view(), name='access_poll'),
    path('<str:code>', views.AccessPollView.as_view(), name='access_poll'),
    
    path('tokens/<int:id>/', views.TokensView.as_view(), name='tokens'),
    path('tokens/<int:id>/download/', views.tokens_view.download_tokens, name='download_tokens'),
    path('tokens/<int:id>/success/', views.tokens_view.tokens_success, name='tokens_success'),
    path('tokens/<int:pk>/delete/', views.tokens_view.TokenDeleteView.as_view(), name='tokens_delete')
]

polls/models/alternative.py
from django.db import models

from .poll import Poll

class Alternative(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.text

polls/models/token.py
from django.db import models

class Token(models.Model):
    poll = models.ForeignKey('TokenizedPoll', on_delete=models.CASCADE)
    token = models.CharField(max_length=255)
    used = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "\""+self.token+"\" -> "+str(self.poll)+" ("+str(self.used)+")"

    def get_password_for_url(self) -> str:
        return self.token.replace(" ", "-")

polls/forms/token_gen_form.py
from django import forms

class TokenGeneratorForm(forms.Form):
    """
    A form class for generating between 1 and 20 random tokens.
    """
    tokens_to_be_generated = forms.IntegerField(
        min_value=1,
        max_value=20,
        label='Inserisci il numero di password da generare'
    )

polls/views/access_poll_view.py
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic.base import RedirectView

from polls.models.mapping import Mapping


class AccessPollView(RedirectView):
    """Redirects to vote or result pages, based on poll state"""

    def get_redirect_url(self, *args, **kwargs):

        mapping = get_object_or_404(Mapping, code=kwargs['code'])
        
        self.request.session['from_code'] = True

        poll = mapping.poll

        if poll.is_ended():
            self.url = reverse('polls:result', kwargs={'id': poll.pk})
        else:
            if 'token' in kwargs:
                redirect_args = {'id': poll.pk, 'token': kwargs['token']}
            else:
                redirect_args={'id': poll.pk}
            self.url = reverse('polls:vote', kwargs=redirect_args)
            
        return super().get_redirect_url(*args, **kwargs)

polls/views/create_poll_view.py
from typing import Any, Optional

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import QuerySet
from django import http
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView

from polls import forms
from polls import models
from polls.services import create_poll_service
from django.urls import reverse


ALTERNATIVE_FORMSET = forms.BaseAlternativeFormSet.get_formset_class()


def select_action(request: http.HttpRequest, poll=None):
    action, queryset_alternatives = ('create', models.Poll.objects.none(
    )) if poll is None else ('edit', poll.alternative_set.all())

    if 'summary' in request.POST:
        return summary(request, action, queryset_alternatives, poll)

    if 'go_back' in request.POST:
        return go_back(request, action, queryset_alternatives, poll)

    if 'save' in request.POST:
        return save(request, action, queryset_alternatives, poll)


def summary(request: http.HttpRequest, action: str, alternatives: QuerySet, poll: Optional[models.Poll] = None):
    form_mainpoll = forms.PollFormMain(request.POST, instance=poll)
    formset_alternatives: forms.BaseAlternativeFormSet = ALTERNATIVE_FORMSET(request.POST, queryset=alternatives)

    if form_mainpoll.is_valid() and formset_alternatives.is_valid():
        form_poll: models.Poll = form_mainpoll.get_temporary_poll()
        
        if action not in request.session:
            request.session[action] = {}

        request.session[action].update({
            'page_1': formset_alternatives.get_form_for_session()
        })

        saved_data = request.session[action].get('page_2')
        saved_data.update(request.POST.dict()) if saved_data is not None else None
        request.session.modified = True
        
        return render(request, f'polls/create_poll/summary_and_options_{action}.html', {
            'alternatives': formset_alternatives.get_alternatives_text_list(),
            'form': forms.PollForm(saved_data, instance = form_poll),
            'mapping_form': forms.PollMappingForm(saved_data, instance = form_poll.mapping),
            'options_form': forms.PollOptionsForm(saved_data, instance = form_poll.polloptions),
        })
    else:
        formset_alternatives._non_form_errors[0] = "Inserisci almeno due alternative." #type: ignore
        for dict in formset_alternatives.errors:
            if 'This field is required.' in str(dict):
                dict['text'] = ''  # type: ignore

        return render(request, f'polls/create_poll/main_page_{action}.html', {
            'form': form_mainpoll,
            'formset': formset_alternatives,
        })


def go_back(request: http.HttpRequest, action: str, alternatives: QuerySet, poll: Optional[models.Poll] = None):

    request.session[action]['page_2'] = request.POST.dict()
    request.session.modified = True
    
    return render(request, f'polls/create_poll/main_page_{action}.html', {
        'form': forms.PollFormMain(request.POST, instance=poll),
        'formset': ALTERNATIVE_FORMSET(request.session[action]['page_1'], queryset=alternatives)
    })


def save(request: http.HttpRequest, action: str, alternatives: QuerySet, poll: Optional[models.Poll] = None):
    form_poll = forms.PollForm(request.POST, instance=poll)
    formset_alternatives: forms.BaseAlternativeFormSet = ALTERNATIVE_FORMSET(request.session[action]['page_1'], queryset=alternatives)
    form_mapping = forms.PollMappingForm(request.POST, instance=poll.mapping if poll is not None else None)
    form_options = forms.PollOptionsForm(request.POST, instance=poll.polloptions if poll is not None else None)

    if all((form_poll.is_valid(), formset_alternatives.is_valid(), form_mapping.is_valid(), form_options.is_valid())):
        saved_poll = create_poll_service(request.user, form_poll, form_mapping, form_options, formset_alternatives) # type: ignore
        if hasattr(saved_poll, models.Poll.AUTH_VOTE_TYPE_FIELDNAME):
            vote_type = 'authenticated'
        elif hasattr(saved_poll, models.Poll.TOKEN_VOTE_TYPE_FIELDNAME):
            vote_type = 'tokenized'
        else:
            vote_type = 'free'
        
        request.session.update({
            'action': action,
            'id': saved_poll.id,
            'code': saved_poll.mapping.code,
            'title': saved_poll.title,
            'end': saved_poll.end.strftime('%d/%m/%Y %H:%M'),
            'vote_type': vote_type
        })
        request.session.modified = True

        return redirect(reverse('polls:poll_created_success'))
    else:
        return render(request, f'polls/create_poll/summary_and_options_{action}.html', {
            'form': form_poll,
            'alternatives': formset_alternatives.get_alternatives_text_list(),
            'mapping_form': form_mapping,
            'options_form': form_options,
        })


class CreatePollView(LoginRequiredMixin, TemplateView):

    def get(self, request: http.HttpRequest, *args, **kwargs):
        return render(request, 'polls/create_poll/main_page_create.html', {
            'form': forms.PollFormMain(),
            'formset': forms.BaseAlternativeFormSet.get_formset_class()(queryset=models.Poll.objects.none())
        })

    def post(self, request: http.HttpRequest, *args, **kwargs):
        return select_action(request)


class EditPollView(LoginRequiredMixin, TemplateView):

    def dispatch(self, request: http.HttpRequest, *args, **kwargs):
        self.__poll: models.Poll = get_object_or_404(models.Poll, id=kwargs['id'])

        if self.__poll.is_active():
            raise PermissionDenied(
                "Non è possibile modificare la scelta perché è in corso la votazione")

        if self.__poll.is_ended():
            raise PermissionDenied(
                "Questa scelta è conclusa e non può essere modificata")

        if not self.__poll.author.__eq__(request.user):
            raise PermissionDenied(
                "Non hai i permessi per modificare questa scelta")

        return super().dispatch(request, *args, **kwargs)

    def get(self, request: http.HttpRequest, *args, **kwargs):
        return render(request, 'polls/create_poll/main_page_edit.html', {
            'form': forms.PollFormMain(instance=self.__poll),
            'formset': forms.BaseAlternativeFormSet.get_formset_class()(queryset=self.__poll.alternative_set.all())
        })

    def post(self, request: http.HttpRequest, *args, **kwargs):
        return select_action(request, self.__poll)

class CreatePollSuccessView(LoginRequiredMixin, TemplateView):

    def get_template_names(self) -> list[str]:
        action = self.request.session.pop('action')
        return [f'polls/{action}_poll_success.html']

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        return {
            'id': self.request.session.pop('id'),
            'code': self.request.session.pop('code'),
            'title': self.request.session.pop('title'),
            'end': self.request.session.pop('end'),
            'vote_type': self.request.session.pop('vote_type')
        }

polls/views/delete_poll_view.py
from typing import Any, Optional

from django.db import models
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView

from polls.models import Poll
from polls.services import check

from django.contrib.auth.mixins import LoginRequiredMixin


class PollDeleteView(LoginRequiredMixin, DeleteView):
    model = Poll
    success_url = reverse_lazy('polls:personal_polls')
    http_method_names = ['post']

    def get_object(self, queryset: Optional[models.query.QuerySet[Any]] = None) -> models.Model:
        poll: Poll = super().get_object(queryset)

        handler = check.CheckPollIsNotStarted(poll)
        handler.set_next(check.CheckPollOwnership(poll, self.request.user))
        passed = handler.handle()

        return passed if passed else poll

polls/views/error_pages.py
from django.shortcuts import render

def error_403(request, exception):
    response = render(request, 'polls/403.html', {'exception': exception})
    response.status_code = 403
    return response

def error_404(request, exception):
    response = render(request, 'polls/404.html', {'exception': exception})
    response.status_code = 404
    return response

def error_500(request):
    response = render(request, 'polls/500.html')
    response.status_code = 500
    return response

polls/views/help_view.py
from django.views.generic.base import TemplateView

class ExplanationGMView(TemplateView):
    template_name = "polls/help/spiegazione_giudizio_maggioritario.html"

class ExplanationSchView(TemplateView):
    template_name = "polls/help/spiegazione_schultze.html"

class HelpSimulatedResultsView(TemplateView):
    template_name: str = 'polls/help/help_simulated_results.html'

class ExplanationCreationPollView(TemplateView):
    template_name: str = 'polls/help/help_advanced_options.html'

polls/views/poll_list.py
from datetime import datetime
from django.urls import reverse_lazy

from typing import Any, Optional, Type

from django import http
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Model, QuerySet
from django.shortcuts import render
from django.http import HttpResponseRedirect

from django.views.generic import FormView, View
from django.views.generic.list import ListView

from polls.forms import SearchPollForm
from polls.models import Poll
from polls.services import PollsListService
from polls.services.active_polls import SearchPollService
from polls.services import check


class IndexView(ListView):
    model: Optional[Type[Model]] = Poll
    paginate_by: int = 6
    template_name: str = 'polls/poll_list.html'

    def __init__(self, **kwargs: Any) -> None:
        self.__active_poll_service = PollsListService()
        super().__init__(**kwargs)

    def get_queryset(self) -> QuerySet[Poll]:
        return self.__active_poll_service.get_ordered_queryset(desc = False)


class SearchView(FormView):
    template_name: str = 'polls/search_poll.html'
    form_class = SearchPollForm

    def form_valid(self, form: SearchPollForm) -> http.HttpResponse:
        return render(self.request, 'polls/includes/poll_list.html', {
            'object_list': form.to_query().search()
        })

    def form_invalid(self, form: SearchPollForm) -> http.HttpResponse:
        return render(self.request, 'polls/includes/search_form.html', {
            'form': form
        })

class PersonalPollsView(LoginRequiredMixin, ListView):
    model: Optional[Type[Model]] = Poll
    paginate_by: int = 6
    template_name: str = 'polls/personal_polls.html'

    def __init__(self, **kwargs: Any) -> None:
        self.__active_poll_service = PollsListService()
        super().__init__(**kwargs)

    def get_queryset(self) -> QuerySet[Poll]:
        return self.__active_poll_service.get_my_polls(self.request.user)

class ClosePollView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request: http.HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponse:
        poll = SearchPollService().search_by_id(kwargs['id'])

        handler = check.CheckPollIsNotEnded(poll)
        handler.set_next(check.CheckPollOwnership(poll, self.request.user))
        handler.handle()
        
        if poll.results_restriction != 2:
            poll.end = datetime.now()
            poll.save()
        return HttpResponseRedirect(reverse_lazy('polls:personal_polls'))
    

class StartPollView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request: http.HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponse:
        poll = SearchPollService().search_by_id(kwargs['id'])
        
        handler = check.CheckPollIsNotStarted(poll)
        handler.set_next(check.CheckPollOwnership(poll, self.request.user))
        handler.handle()
        
        poll.start = datetime.now()
        poll.save()
        return HttpResponseRedirect(reverse_lazy('polls:personal_polls'))
        

templates/polls/results/result_GM.html
{% extends 'layouts/base.html' %}
{% load lookup_filter %}
{% load static %}

{% block title %} {{block.super}} | Risultati {% endblock title %}

{% block stylesheets %} 
<style>
  /* bootstrap hack: fix content width inside hidden tabs */
  .tab-content > .tab-pane,
  .pill-content > .pill-pane {
  display: block;     /* undo display:none          */
  height: 0;          /* height:0 is also invisible */ 
  overflow-y: hidden; /* no-overflow                */
  }
  .tab-content > .active,
  .pill-content > .active {
  height: auto;       /* let the content decide it  */
  } /* bootstrap hack end */

  #textbox {
    display: flex;
    justify-content: space-between;
  }

</style>
{% endblock stylesheets %}


{% block content %}
<div class="pcoded-main-container">
  <div class="pcoded-content">
    <div class="page-header">
      <div class="page-block">
        <div class="row align-items-center">
          <div class="col-md-12">
            <div class="page-header-title">
              <h3 class="m-b-10">Risultati scelta</h3>
            </div>
            <ul class="breadcrumb">
              <li class="breadcrumb-item"><a href="/"><em class="feather icon-home"></em></a></li>
              <li class="breadcrumb-item">Risultati</li>
              <li class="breadcrumb-item"><strong>{{ poll.title }}</strong></li>
            </ul>
          </div>
        </div>
      </div>
    </div>


    <!-- [ Riepilogo ] start -->
    {% if poll.get_type != "Giudizio maggioritario" %}
    <div class="card bg-white">
      <div class="card-body">
        <h5 class="card-header text-warning">Stai vedendo una simulazione dei risultati</h5>
        <div class="card-body">
          <p>Questa pagina simula i risultati che si sarebbero potuti ottenere usando un metodo di voto diverso, il <b>giudizio maggioritario</b>.</br>
            Per visualizzare i risultati reali, <a href="{% url 'polls:result' id=poll.id %}" class="link-warning">premi su questo collegamento</a>.</br></p>
            {% if include_synthetic %}
            <a href="{% url 'polls:result_MJ_realonly' id=poll.id include_synthetic="realonly" %}" class="lead">
              <i class="bi bi-check-square-fill link-warning"></i>
              <label class="text-black">Includi i voti sintetici nel calcolo dei risultati</label>
            </a>
            {% else %}
            <a href="{% url 'polls:result_MJ' id=poll.id %}" class="lead">
              <i class="bi bi-square link-warning"></i>
              <label class="text-black">Includi i voti sintetici nel calcolo dei risultati</label>
            </a>
            {% endif %}
          </div>
        <div class="card-footer">
          <p>Se vuoi sapere come è stata calcolata questa simulazione e cosa sono i voti sintetici, <a href="{% url 'polls:help_simulated_results' %}" class="link-info">qui trovi la spiegazione</a>.</p>
        </div>
      </div>
    </div>
    {% endif %}

    {% include 'polls/includes/riepilogo.html'%}

    {% if poll.is_active %}
      {% if poll.results_restriction == 1 %}
      <!-- {{poll.results_restriction}}-show -->
      {% include 'polls/includes/classifica_grafici_GM.html' %}
      {% endif %}

      {% if poll.results_restriction == 2 %}
          {% if user.is_authenticated and user == poll.author %}
          <!-- {{poll.results_restriction}}-show -->
          {% include 'polls/includes/classifica_grafici_GM.html' %}
          {% elif user != poll.author %}
          <!-- {{poll.results_restriction}}-lock -->
          <div class="card text-center">
            <div class="card-body">
              <h5 class="mt-4">Potrai vedere i risultati della scelta solo quando saranno terminate le votazioni</h5>
              <br>
              <i class="fas fa-lock fa-10x"></i>
            </div>
          </div>
          {%endif%}
      {% endif %}

      {% if poll.results_restriction == 3%}
          <!-- {{poll.results_restriction}}-lock -->
          <div class="card text-center">
            <div class="card-body">
              <h5 class="mt-4">Potrai vedere i risultati della scelta solo quando saranno terminate le votazioni</h5>
              <br>
              <i class="fas fa-lock fa-10x"></i>
            </div>
          </div>
      {% endif %}
    {% endif %}

    {% if poll.is_ended %}
    {% include 'polls/includes/classifica_grafici_GM.html' %}
    {% endif %}    

    <hr>

    <div class="row">
      <div class="col text-center">
        {% if poll.get_type != "Giudizio maggioritario" %}
        <a role="button" href="{% url 'polls:result' id=poll.id %}" class="btn btn-block btn-primary">Torna ai risultati reali</a>
        {% endif %}
        <a role="button" href={% url 'polls:index' %} class="btn btn-block btn-secondary">Torna alla home</a>
      </div>
    </div>
  </div>
  {% include 'polls/includes/footer.html' %}
</div>

{% include 'polls/includes/modal_spiegazione_giudizio_maggioritario.html'%}

{% endblock content %}


{% block javascripts %}

{% if poll.is_active %}
    {% if poll.results_restriction == 1 %}
    <!-- {{poll.results_restriction}}-show -->
      {% include 'polls/results/script_GM.html' %}
    {% endif %}

    {% if poll.results_restriction == 2 %}
        {% if user.is_authenticated and user == poll.author %}
        <!-- {{poll.results_restriction}}-show -->
          {% include 'polls/results/script_GM.html' %}
        {%endif%}
    {% endif %}
{% endif %}
{% if not poll.is_active %}
  {% include 'polls/results/script_GM.html' %}
{% endif %}

{% endblock javascripts %}

templates/polls/results/result_SH.html
{% extends 'layouts/base.html' %}
{% load lookup_filter %}
{% load static %}

{% block title %} {{block.super}} | Risultati {% endblock title %}

{% block stylesheets %} 
<style>
  /* bootstrap hack: fix content width inside hidden tabs */
  .tab-content > .tab-pane,
  .pill-content > .pill-pane {
  display: block;     /* undo display:none          */
  height: 0;          /* height:0 is also invisible */ 
  overflow-y: hidden; /* no-overflow                */
  }
  .tab-content > .active,
  .pill-content > .active {
  height: auto;       /* let the content decide it  */
  } /* bootstrap hack end */

  #textbox {
    display: flex;
    justify-content: space-between;
  }

</style>
{% endblock stylesheets %}

{% block content %}
<div class="pcoded-main-container">
  <div class="pcoded-content">
    <div class="page-header">
      <div class="page-block">
        <div class="row align-items-center">
          <div class="col-md-12">
            <div class="page-header-title">
              <h3 class="m-b-10">Risultati scelta</h3>
            </div>
            <ul class="breadcrumb">
              <li class="breadcrumb-item"><a href="/"><em class="feather icon-home"></em></a></li>
              <li class="breadcrumb-item">Risultati</li>
              <li class="breadcrumb-item"><strong>{{ poll.title }}</strong></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    {% include 'polls/includes/riepilogo.html'%}

    {% if poll.is_active %}
      {% if poll.results_restriction == 1 %}
      <!-- {{poll.results_restriction}}-show -->
      {% include 'polls/includes/classifica_grafici_SH.html' %}
      {% endif %}

      {% if poll.results_restriction == 2 %}
          {% if user.is_authenticated and user == poll.author %}
          <!-- {{poll.results_restriction}}-show -->
            {% include 'polls/includes/classifica_grafici_SH.html' %}
          {% elif user != poll.author %}
          <!-- {{poll.results_restriction}}-lock -->
          <div class="card text-center">
            <div class="card-body">
              <h5 class="mt-4">Potrai vedere i risultati della scelta solo quando saranno terminate le votazioni</h5>
              <br>
              <i class="fas fa-lock fa-10x"></i>
            </div>
          </div>
          {%endif%}
      {% endif %}

      {% if poll.results_restriction == 3 %}
          <!-- {{poll.results_restriction}}-lock -->
          <div class="card text-center">
            <div class="card-body">
              <h5 class="mt-4">Potrai vedere i risultati della scelta solo quando saranno terminate le votazioni</h5>
              <br>
              <i class="fas fa-lock fa-10x"></i>
            </div>
          </div>
      {% endif %}
    {% endif %}

    {% if poll.is_ended %}
      {% include 'polls/includes/classifica_grafici_SH.html' %}
    {% endif %}    

    <hr>

    <div class="row">
      <div class="col text-center">
        <a role="button" href={% url 'polls:index' %} class="btn btn-block btn-primary">Torna alla home</a>
      </div>
    </div>
  </div>
  {% include 'polls/includes/footer.html' %}
</div>

{% include 'polls/includes/modal_spiegazione_metodo_shultze.html'%}

{% endblock content %}


{% block javascripts %}

{% if poll.is_active %}
    {% if poll.results_restriction == 1 %}
    <!-- {{poll.results_restriction}}-show -->
      {% include 'polls/results/script_SH.html' %}
    {% endif %}

    {% if poll.results_restriction == 2 %}
        {% if user.is_authenticated and user == poll.author %}
        <!-- {{poll.results_restriction}}-show -->
          {% include 'polls/results/script_SH.html' %}
        {%endif%}
    {% endif %}
{% endif %}
{% if not poll.is_active %}
  {% include 'polls/results/script_SH.html' %}
{% endif %}

{% endblock javascripts %}

templates/polls/results/script_SP.html
{% load static %}

<script src={% static 'js/plugins/apexcharts.min.js' %}></script>
<script>
  var options = {
    series: [{
      name: 'Preferenze',
      data: [
        {% for vote in results %}
        {
          x: "{{ vote.text|safe }}",
          y: {{ vote.count }},
        },
        {% endfor %}
      ]
    }],
  chart: {
    height: 350,
    type: 'bar',
    zoom: {
      enabled: true
    }
  },
  responsive: [{
    breakpoint: 480,
    options: {
      legend: {
        position: 'bottom',
        offsetX: -10,
        offsetY: 0
      }
    }
  }],
  plotOptions: {
    bar: {
      horizontal: false,
        columnWidth: '55%',
          endingShape: 'rounded'
    },
  },
  dataLabels: {
    enabled: true,
        style: {
          fontSize: '12px',
          colors: ["#FFFFFF"]
        }
  },
  stroke: {
    show: true,
      width: 2,
        colors: ['transparent']
  },
  xaxis: {
    type: 'category'
  },
  yaxis: {
    title: {
      text: 'numero di preferenze'
    }
  },
  fill: {
    opacity: 1
  },
  tooltip: {
    y: {
      formatter: function (val) {
        return val
      }
    }
  }
  };

  var chart = new ApexCharts(document.querySelector("#bar-chart"), options);
  chart.render();
</script>

<script>
  var options = {
    chart: {
      height: 350,
      type: 'pie',
    },
    series: [{% for vote in results %}{{ vote.count }}, {% endfor %}],
    labels: [{% for vote in results %}"{{ vote.text|safe }}", {% endfor %}],
    legend: {
      show: true,
      position: 'bottom',
    },
    fill: {
      type: 'gradient',
      gradient: {
          shade: 'light',
          inverseColors: true,
      }
    },
    dataLabels: {
      enabled: true,
      dropShadow: {
          enabled: false,
      }
    },
    responsive: [{
      breakpoint: 480,
      options: {
          legend: {
              position: 'bottom'
          }
      }
    }]
  };

  var chart = new ApexCharts(document.querySelector("#pie-chart"), options);
  chart.render();
</script>